name: eco_walk
description: "ğŸŒ A walking tracker app that promotes environmental awareness by highlighting significant landmarks, sharing fun facts, and rewarding users with leaf points for their exploration. ğŸš¶â€â™‚ï¸ğŸƒ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

# Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  cloud_functions: ^5.3.1
  firebase_storage: ^12.4.1
  google_sign_in: ^6.2.2
  firebase_cached_image: ^0.6.3

# Native APIs
  geolocator: ^13.0.2
  mapbox_maps_flutter: ^2.5.1
  shared_preferences: ^2.4.0

# Utils
  http: ^1.3.0
  intl: ^0.20.2
  icons_plus: ^5.0.0
  image: ^4.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/puck.png
    - assets/point.png